"""Build a reference list from DOIs, with every field fetched, never typed.

    python3 tools/cite.py --in refs_in.json --out refs

MANUSCRIPT_RULES R12d: the citation string is generated by a program from what
Crossref and PubMed return. Nothing is typed by hand, because "只要是手打的，
就會有一筆錯" -- the rule's own example is a reference list where four fields
were filled from memory and three of the four were wrong, and where switching to
program generation made 41 entries correct in one pass.

The three stages R12d prescribes:

  1. HUMAN   choose the works, group them, write why each is cited.
             That is judgment and is NOT done here -- this tool consumes a list
             of DOIs and reasons that a person wrote.
  2. PROGRAM fetch metadata from Crossref (`api.crossref.org/works/<DOI>`) and
             PubMed, read the update relations for retractions and corrections,
             save the raw JSON.
  3. PROGRAM render citation strings from that JSON.

Outputs `<out>.json` (raw), `<out>_table.md` (the per-entry check table) and
`<out>_strings.md` (rendered citations + the verification statement).

Journal abbreviations come from PubMed's `iso_abbreviation` where available, per
R12d ("Sensors (Basel)" not "Sensors"); Crossref's short-container-title is the
fallback and is marked as such.

The rendered style is Harvard (alphabetical), which is what Physiological
Measurement requires. The target journal is an R1 decision that has not been
made, so Vancouver is rendered alongside and the JSON stays style-agnostic.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import time
import urllib.parse
import urllib.request
from pathlib import Path

UA = "cite.py (mailto:kklven@gmail.com)"
CROSSREF = "https://api.crossref.org/works/"
EUTILS = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/"


def get(url: str, tries: int = 3) -> dict | str:
    for k in range(tries):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": UA})
            with urllib.request.urlopen(req, timeout=30) as r:
                body = r.read().decode("utf-8", "replace")
            return json.loads(body) if body.lstrip().startswith(("{", "[")) else body
        except Exception as e:
            if k == tries - 1:
                raise
            time.sleep(2 * (k + 1))
    raise RuntimeError("unreachable")


def crossref(doi: str) -> dict:
    return get(CROSSREF + urllib.parse.quote(doi, safe=""))["message"]


def pubmed(doi: str) -> dict:
    """PMID plus the ISO journal abbreviation, which Crossref does not carry."""
    q = urllib.parse.urlencode({"db": "pubmed", "term": f"{doi}[DOI]",
                                "retmode": "json"})
    hits = get(f"{EUTILS}esearch.fcgi?{q}").get("esearchresult", {}).get("idlist", [])
    if not hits:
        return {}
    pmid = hits[0]
    s = get(f"{EUTILS}esummary.fcgi?db=pubmed&id={pmid}&retmode=json")
    rec = s.get("result", {}).get(pmid, {})
    return {"pmid": pmid, "iso_abbreviation": rec.get("source"),
            "pubmed_title": rec.get("title"), "pubdate": rec.get("pubdate")}


def authors(msg: dict) -> list[str]:
    """Full author list in the order the publisher recorded it. R12c: the author
    list is the field least likely to be caught by eye when wrong."""
    out = []
    for a in msg.get("author", []) or []:
        fam, giv = a.get("family"), a.get("given")
        if fam and giv:
            out.append(f"{fam} {''.join(p[0] for p in giv.replace('-', ' ').split())}")
        elif fam:
            out.append(fam)
        elif a.get("name"):
            out.append(a["name"])
    return out


def year(msg: dict) -> str:
    for k in ("published-print", "published-online", "issued", "created"):
        p = msg.get(k, {}).get("date-parts", [[None]])[0]
        if p and p[0]:
            return str(p[0])
    return "n.d."


def pages(msg: dict) -> str:
    return msg.get("page") or msg.get("article-number") or ""


def render_harvard(e: dict) -> str:
    a = e["authors"]
    who = (a[0] if len(a) == 1 else
           f"{a[0]} and {a[1]}" if len(a) == 2 else
           f"{a[0]} et al" if len(a) > 6 else
           ", ".join(a[:-1]) + f" and {a[-1]}")
    bits = [f"{who} {e['year']}", e["title"].replace("\xa0", " "), f"*{e['journal']}*"]
    tail = " ".join(x for x in [e.get("volume"), pagesep(e)] if x)
    s = " ".join(bits) + (f" **{e['volume']}** {pagesep(e)}" if e.get("volume") else "")
    return f"{s} (doi:{e['doi']})".replace("  ", " ")


def pagesep(e: dict) -> str:
    return e.get("pages") or ""


def render_vancouver(e: dict, n: int) -> str:
    a = e["authors"]
    who = ", ".join(a[:6]) + (", et al" if len(a) > 6 else "")
    v = e.get("volume") or ""
    p = e.get("pages") or ""
    return (f"{n}. {who}. {e['title'].replace(chr(160), ' ')}. {e['journal']}. {e['year']}"
            f"{';' + v if v else ''}{':' + p if p else ''}. doi:{e['doi']}")


# ---- Nature style (Scientific Reports), added 2026-10-06 ----------------
# Journal abbreviation tokens that are whole words and take no full stop. Every other
# token of the NLM abbreviation is an abbreviation and takes one (Nature house style).
NATURE_FULL_WORDS = {"IEEE", "Imaging", "Neuroimage", "Machine", "Learning", "Respiration",
                     "Thorax", "PLoS", "One", "Image", "Care", "Sensors", "Pattern",
                     "Biometrics", "Bulletin", "Methods", "Programs", "USA", "(1985)",
                     "(Basel)", "Vision", "Conference", "on", "Computer", "and", "Recognition",
                     "Advances", "in", "Neural", "Information", "Processing", "Systems",
                     "Lecture", "Notes", "Science", "Proceedings", "of", "the", "British",
                     "2016", "2018", "2019", "2020", "35", "(CVPR)", "IEEE/CVF"}
NATURE_JOURNAL_SPECIAL = {"Proc Natl Acad Sci U S A": "Proc. Natl Acad. Sci. USA"}


def nature_journal(j: str) -> str:
    if j in NATURE_JOURNAL_SPECIAL:
        return NATURE_JOURNAL_SPECIAL[j]
    out = []
    for tok in j.split():
        if tok in NATURE_FULL_WORDS or tok.endswith("."):
            out.append(tok)
        else:
            out.append(tok + ".")
    return " ".join(out)


def nature_author(a: str) -> str:
    """'Hamilton SJ' -> 'Hamilton, S. J.'; 'De Palma A' -> 'De Palma, A.'."""
    parts = a.split()
    if len(parts) < 2:
        return a
    fam, ini = " ".join(parts[:-1]), parts[-1]
    return f"{fam}, " + " ".join(f"{c}." for c in ini)


def render_nature(e: dict, n: int) -> str:
    """Nature referencing style as the Scientific Reports guidelines state it
    (2026-10-06): numbered; all authors unless six or more, then first author et al.;
    'Surname, I. N.' with '&' before the last; article title roman, as in the work;
    journal abbreviated with full stops, italic; volume bold; pages; year in brackets;
    online-only items carry the DOI after the article number."""
    a = [nature_author(x) for x in e["authors"]]
    who = f"{a[0]} et al." if len(a) >= 6 else (a[0] if len(a) == 1 else ", ".join(a[:-1]) + f" & {a[-1]}")
    title = e["title"].replace("\xa0", " ").rstrip(".")
    end = "" if title.endswith("?") else "."
    pages = (e.get("pages") or "").replace("-", "\u2013")
    vol = e.get("volume") or ""
    if e.get("type") in ("proceedings-article", "book-chapter"):
        cont = e.get("container_full") or e["journal"]
        volpart = f" **{vol}**," if vol else ""
        return f"{n}. {who} {title}{end} In *{cont}*{volpart} {pages} ({e['year']}).".replace("  ", " ")
    j = nature_journal(e["journal"])
    online_only = bool(pages) and "\u2013" not in pages
    tail = f"{pages}; {e['doi']}" if online_only else pages
    volpart = f" **{vol}**," if vol else ""
    return f"{n}. {who} {title}{end} *{j}*{volpart} {tail} ({e['year']}).".replace("  ", " ").replace(", (", " (")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--in", dest="inp", required=True, type=Path,
                    help="JSON list of {key, doi, why} written by a person")
    ap.add_argument("--out", required=True, type=Path)
    a = ap.parse_args()

    spec = json.loads(a.inp.read_text())
    entries, flags = [], {"retracted": [], "corrected": [], "no_pubmed": []}

    for item in spec:
        doi = item["doi"]
        print(f"  fetching {doi}")
        m = crossref(doi)
        pm = pubmed(doi)
        if not pm:
            flags["no_pubmed"].append(doi)

        # retraction / correction relations, both directions
        rel = m.get("relation", {}) or {}
        upd = m.get("update-to", []) or []
        updated_by = rel.get("is-corrected-by", []) + rel.get("is-retracted-by", [])
        kind = [u.get("type") for u in upd]
        if any("retract" in str(k).lower() for k in kind) or rel.get("is-retracted-by"):
            flags["retracted"].append(doi)
        if any("correct" in str(k).lower() for k in kind) or rel.get("is-corrected-by"):
            flags["corrected"].append(doi)

        e = {
            "key": item["key"], "why": item.get("why", ""), "doi": doi,
            "authors": authors(m),
            "title": (m.get("title") or [""])[0].strip(),
            "journal": pm.get("iso_abbreviation")
                       or (m.get("short-container-title") or [""])[0]
                       or (m.get("container-title") or [""])[0],
            "journal_source": "pubmed:iso_abbreviation" if pm.get("iso_abbreviation")
                              else "crossref:short-container-title",
            "container_full": (m.get("container-title") or [""])[0],
            "year": year(m), "volume": m.get("volume"), "issue": m.get("issue"),
            "pages": pages(m), "pmid": pm.get("pmid"),
            "publisher": m.get("publisher"), "type": m.get("type"),
            "update_relations": {"update-to": upd, "updated-by": updated_by},
        }
        entries.append(e)
        time.sleep(0.4)

    entries.sort(key=lambda e: (e["authors"][0] if e["authors"] else "", e["year"]))
    stamp = dt.datetime.now().strftime("%Y-%m-%d %H:%M")
    a.out.parent.mkdir(parents=True, exist_ok=True)
    Path(f"{a.out}.json").write_text(json.dumps(entries, ensure_ascii=False, indent=2))

    # ---- per-entry check table (R12d) ----------------------------------
    t = [f"# 引用逐筆核對表\n",
         f"產生時間 {stamp}　來源 Crossref REST API + NCBI E-utilities",
         f"　由 `tools/cite.py` 生成，**任何一個欄位都不是手打的**\n"]
    for e in entries:
        t.append(f"## {e['key']}\n")
        t.append(f"| 欄位 | 資料庫回傳 |\n|---|---|")
        t.append(f"| DOI | `{e['doi']}` |")
        t.append(f"| 作者（原始順序） | {', '.join(e['authors'])} |")
        t.append(f"| 題名 | {e['title']} |")
        t.append(f"| 期刊全名 | {e['container_full']} |")
        t.append(f"| 期刊縮寫 | {e['journal']} ({e['journal_source']}) |")
        t.append(f"| 年／卷／期／頁 | {e['year']} / {e['volume'] or '—'} / "
                 f"{e['issue'] or '—'} / {e['pages'] or '—'} |")
        t.append(f"| PMID | {e['pmid'] or '未收錄於 PubMed'} |")
        t.append(f"| 撤稿／更正關係 | {e['update_relations'] or '無'} |")
        t.append(f"\n引用理由（人工）：{e['why']}\n")
    Path(f"{a.out}_table.md").write_text("\n".join(t))

    # ---- rendered strings + verification statement ---------------------
    s = [f"# 引用字串（程式生成）\n",
         "## Harvard（字母序）— Physiological Measurement 要求的格式\n"]
    for e in entries:
        s.append(f"- {render_harvard(e)}")
    s.append("\n## Vancouver（編號制）— 若投稿期刊改變\n")
    for i, e in enumerate(entries, 1):
        s.append(f"{render_vancouver(e, i)}")
    s.append("\n## Nature（編號制，Scientific Reports）\n")
    for i, e in enumerate(entries, 1):
        s.append(f"{render_nature(e, i)}")
    s.append(f"""
---

## 核對聲明（MANUSCRIPT_RULES R12d）

- **筆數**：{len(entries)}
- **時間**：{stamp}
- **API**：Crossref REST (`api.crossref.org/works/<DOI>`)；
  期刊縮寫取自 NCBI E-utilities 的 `iso_abbreviation`
- **相符情形**：全部 {len(entries)} 筆均由 DOI 直接解析成功，
  作者列、題名、期刊、年、卷、期、頁、DOI 逐欄由 API 回傳，未經手打
- **撤稿**：{len(flags['retracted'])} 篇{'　→ ' + ', '.join(flags['retracted']) if flags['retracted'] else ''}
- **更正**：{len(flags['corrected'])} 篇{'　→ ' + ', '.join(flags['corrected']) if flags['corrected'] else ''}
- **未收錄於 PubMed**：{len(flags['no_pubmed'])} 篇{'　→ ' + ', '.join(flags['no_pubmed']) if flags['no_pubmed'] else ''}
  （此類期刊縮寫改用 Crossref 的 short-container-title，已於逐筆表標註來源）

逐筆核對表：`{a.out.name}_table.md`　原始 JSON：`{a.out.name}.json`
""")
    Path(f"{a.out}_strings.md").write_text("\n".join(s))
    print(f"\n  {len(entries)} 筆　撤稿 {len(flags['retracted'])}　"
          f"更正 {len(flags['corrected'])}　未收錄 PubMed {len(flags['no_pubmed'])}")
    print(f"  wrote {a.out}.json / {a.out}_table.md / {a.out}_strings.md")


if __name__ == "__main__":
    main()
