#!/usr/bin/env bash
# PREREGISTRATION_RECON.md sections 4, 5, 9. Run on the MINI (the machine that trained
# every other run of this line), from ~/work/sunet_mini:
#
#   nohup caffeinate -i bash tools/run_recon_mini.sh ~/work/sunet_sweep > recon_train.log 2>&1 &
#
# Inputs (rsynced from the Air, generated by tools/gen_recon_full.m and
# tools/build_mixed_dataset.py):
#   <sweep>/v2_full_snr20_gn/dataset.mat, <sweep>/v2_full_snr20_bp/dataset.mat,
#   <sweep>/v2_full_snr20_mixed/dataset.mat
# Registered: D and B_wide, seeds 0-29, every training constant unchanged.
# Two processes, as for the addendum (the mini's sweet spot):
#   A: GN seeds 0-29, then mixed seeds 0-14      B: BP seeds 0-29, then mixed seeds 15-29
set -euo pipefail
SWEEP="${1:?usage: run_recon_mini.sh <sweep-root>}"
cd "$(dirname "$0")/.."
for f in v2_full_snr20_gn v2_full_snr20_bp v2_full_snr20_mixed; do
  [ -f "$SWEEP/$f/dataset.mat" ] || { echo "missing $SWEEP/$f/dataset.mat"; exit 1; }
done
H=$(shasum -a 256 PREREGISTRATION_RECON.md | cut -d' ' -f1)
grep -q "$H" PREREGISTRATION_RECON.sha256 || { echo "PREREGISTRATION_RECON.md hash $H not in .sha256 — file changed after registration"; exit 1; }
echo "prereg hash $H matches the registered state"; date

train () {  # <dataset> <out> <seeds...>
  local ds=$1 out=$2; shift 2
  python3 tools/train_arms.py --data "$SWEEP/$ds/dataset.mat" --arms D B_wide --seeds "$@" \
      --out "$out" --prereg PREREGISTRATION_RECON.md
}
( train v2_full_snr20_gn    runs_recon_gn    $(seq 0 29) && train v2_full_snr20_mixed runs_recon_mixed $(seq 0 14)  ) > recon_A.log 2>&1 &
( train v2_full_snr20_bp    runs_recon_bp    $(seq 0 29) && train v2_full_snr20_mixed runs_recon_mixed $(seq 15 29) ) > recon_B.log 2>&1 &
wait
echo "training done"; date
for d in runs_recon_gn runs_recon_bp runs_recon_mixed; do echo "$d: $(ls $d/*_seed*.pt | wc -l) checkpoints"; done
bash tools/eval_recon_matrix.sh "$SWEEP"
